DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS MATRICULA;
DROP TABLE IF EXISTS GRUPO;
DROP TABLE IF EXISTS ALUMNO;
DROP TABLE IF EXISTS CICLO;
DROP TABLE IF EXISTS PROFESOR;
DROP TABLE IF EXISTS CARRERA_CURSO;
DROP TABLE IF EXISTS CURSO;
DROP TABLE IF EXISTS CARRERA;

CREATE TABLE CARRERA (
                         CODIGO_CARRERA VARCHAR(20) PRIMARY KEY,
                         NOMBRE VARCHAR(100) NOT NULL,
                         TITULO VARCHAR(100) NOT NULL
);

CREATE TABLE CURSO (
                       CODIGO_CURSO VARCHAR(20) PRIMARY KEY,
                       NOMBRE VARCHAR(100) NOT NULL,
                       CREDITOS INTEGER NOT NULL,
                       HORAS_SEMANALES INTEGER NOT NULL
);

CREATE TABLE CARRERA_CURSO (
                               CARRERA_CURSO_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                               CODIGO_CARRERA VARCHAR(20) NOT NULL,
                               CODIGO_CURSO VARCHAR(20) NOT NULL,
                               ANIO INTEGER NOT NULL,
                               CICLO INTEGER NOT NULL,
                               ORDEN INTEGER NOT NULL,
                               FOREIGN KEY (CODIGO_CARRERA) REFERENCES CARRERA(CODIGO_CARRERA),
                               FOREIGN KEY (CODIGO_CURSO) REFERENCES CURSO(CODIGO_CURSO)
);

CREATE TABLE PROFESOR (
                          CEDULA VARCHAR(20) PRIMARY KEY,
                          NOMBRE VARCHAR(100) NOT NULL,
                          TELEFONO VARCHAR(20),
                          EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE CICLO (
                       CICLO_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                       ANIO INTEGER NOT NULL,
                       NUMERO INTEGER NOT NULL CHECK (NUMERO IN (1, 2)),
                       FECHA_INICIO DATE NOT NULL,
                       FECHA_FIN DATE NOT NULL,
                       ACTIVO BOOLEAN DEFAULT FALSE
);

CREATE TABLE ALUMNO (
                        CEDULA VARCHAR(20) PRIMARY KEY,
                        NOMBRE VARCHAR(100) NOT NULL,
                        TELEFONO VARCHAR(20),
                        EMAIL VARCHAR(100) NOT NULL,
                        FECHA_NACIMIENTO DATE NOT NULL,
                        CODIGO_CARRERA VARCHAR(20) NOT NULL,
                        FOREIGN KEY (CODIGO_CARRERA) REFERENCES CARRERA(CODIGO_CARRERA)
);

CREATE TABLE GRUPO (
                       GRUPO_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                       ANIO_CICLO INTEGER NOT NULL,
                       NUMERO_CICLO INTEGER NOT NULL,
                       CODIGO_CURSO VARCHAR(20) NOT NULL,
                       NUMERO_GRUPO INTEGER NOT NULL,
                       HORARIO VARCHAR(200) NOT NULL,
                       CEDULA_PROFESOR VARCHAR(20) NOT NULL,
                       FOREIGN KEY (ANIO_CICLO, NUMERO_CICLO) REFERENCES CICLO(ANIO, NUMERO),
                       FOREIGN KEY (CODIGO_CURSO) REFERENCES CURSO(CODIGO_CURSO),
                       FOREIGN KEY (CEDULA_PROFESOR) REFERENCES PROFESOR(CEDULA)
);

CREATE TABLE MATRICULA (
                           MATRICULA_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                           ANIO_CICLO INTEGER NOT NULL,
                           NUMERO_CICLO INTEGER NOT NULL,
                           CODIGO_CURSO VARCHAR(20) NOT NULL,
                           NUMERO_GRUPO INTEGER NOT NULL,
                           CEDULA_ALUMNO VARCHAR(20) NOT NULL,
                           NOTA DECIMAL(5,2) DEFAULT NULL,
                           FOREIGN KEY (ANIO_CICLO, NUMERO_CICLO, CODIGO_CURSO, NUMERO_GRUPO) REFERENCES GRUPO(ANIO_CICLO, NUMERO_CICLO, CODIGO_CURSO, NUMERO_GRUPO),
                           FOREIGN KEY (CEDULA_ALUMNO) REFERENCES ALUMNO(CEDULA)
);

CREATE TABLE USUARIO (
                         CEDULA VARCHAR(20) PRIMARY KEY,
                         CLAVE VARCHAR(100) NOT NULL,
                         TIPO_USUARIO VARCHAR(20) NOT NULL CHECK (TIPO_USUARIO IN ('ADMINISTRADOR', 'MATRICULADOR', 'PROFESOR', 'ALUMNO'))
);